# 异步测试
## 测试异步代码
不管是 Async/Await 还是 Promise 都需要在Promise对象前面加上 return/await。如果忽略，测试时不会等待Promise状态改变前结束测试
### Async/Await
可以在测试中使用 async 和 await。 写异步测试用例时，可以在传递给test的函数前面加上async。
```javascript
test('the data is peanut butter', async () => {
  const data = await fetchData()
  expect(data).toBe('peanut butter')
})
```
### Promise
```javascript
test('the data is peanut butter', () => {
  return fetchData().then(data => {
    expect(data).toBe('peanut butter')
  })
})
```
### 测试异步异常
对于Promise来说，可以使用`.catch`捕获异常，而 Async/Await 可以使用`try...catch...`捕获异常。确保添加 expect.assertions 来验证一定数量的断言被调用。 否则，一个成功状态的Promise不会让测试用例失败。
```javascript
test('the fetch fails with an error', () => {
  expect.assertions(1)
  return fetchData().catch(e => expect(e).toMatch('error'))
})
```
如果不使用`expect.assertions`，当`fetchData`成功时，不会执行`.catch`里面的测试用例，导致测试用例执行成功。
### 测试定时器、延时器
假设想测试下面定时器中的回调
```javascript
// timer.js
export const timer = (cb) => {
    setTimeout(() => {
        cb()
    }, 3000)
}
```
如果直接对定时器进行测试会出现异常
```javascript
import {timer} from './demo'

test('timer 测试', () => {
    timer(() => {
        expect(1).toBe(2) // success，实际上是不对的
    })
})
```
这个时候可以使用done方法，等定时器执行完成之后再结束测试
```javascript
test('timer 测试', (done) => {
    timer(() => {
        expect(2).toBe(1) // error
        done()
    })
})
```
使用done方法虽然能让测试用例执行结果没有问题，但是每次都需要等待定时器执行
#### 启用假定时器
此时可以通过`jest.useFakeTimers`方法来启动一个假定时器，来取代`setTimeout`和其他计时器函数的原始实现。通过`jest.useRealTimers()`可以恢复计时器函数的原始实现

启动假定时器后，还需要将时间“快进”到正确的时间点，这样就可以避免长时间等待
##### 运行所有定时器
通过`jest.runAllTimers()`可以直接立马执行所有定时器
```javascript
const timer = (cb) => {
    // 嵌套定时器
    setTimeout(() => {
        cb()
        setTimeout(() => {
            cb()
        }, 3000)
    }, 3000)
}
// 开启假定时器
jest.useFakeTimers()

test('timer 测试', () => {
    const fn = jest.fn()
    timer(fn)
  	// 运行所有定时器
    jest.runAllTimers()
    expect(fn).toHaveBeenCalledTimes(2) // success
})
```
##### 仅运行等待中的定时器
还有一种情况，比如使用`setInterval`或递归的`setTimeout`时（在自己的回调中设置一个新定时器的定时器），对于这些情况，运行所有计时器将是一个无休止的循环，并抛出错误:“运行100000个计时器后中止，假设是一个无限循环!”

为了解决上述情况，可以使用`jest.runOnlyPendingTimers()`方法，仅运行等待中的定时器
```javascript
const timer = (cb) => {
    // 嵌套定时器
    setTimeout(() => {
        cb()
        setTimeout(() => {
            cb()
        }, 3000)
    }, 3000)
}
// 开启假定时器
jest.useFakeTimers()

test('timer 测试', () => {
    const fn = jest.fn()
    timer(fn)
    jest.runOnlyPendingTimers()
    expect(fn).toHaveBeenCalledTimes(1) // success
})
```
##### 跳转到指定时间点（推荐）
另一种可选方式是使用`jest. advancertimersbytime (ms)`直接将时间“改到”未来的某时间点
```javascript
const timer = (cb) => {
    // 嵌套定时器
    setTimeout(() => {
        cb()
        setTimeout(() => {
            cb()
        }, 3000)
    }, 3000)
}
// 开启假定时器
jest.useFakeTimers()

test('timer 测试', () => {
    const fn = jest.fn()
    timer(fn)
    // 跳到 3s 之后
    jest.advanceTimersByTime(3000)
    expect(fn).toHaveBeenCalledTimes(1) // success
    // 再跳 3s
    jest.advanceTimersByTime(3000)
    expect(fn).toHaveBeenCalledTimes(2) // success
})
```
##### 清除所有等待状态下的定时器
```javascript
jest.clearAllTimers()
```
## 异步匹配器
### .resolves
使用`.resolves`匹配器，Jest 会等待这一 Promise 来解决。 如果 Promise 被拒绝，则测试将自动失败
```javascript
test('the data is peanut butter', () => {
  return expect(fetchData()).resolves.toBe('peanut butter')
})
```
一定不要忘记把整个断言作为返回值返回⸺如果忘了return语句的话，在 fetchData 返回的这个 promise 变更为成功状态前，测试就已经被视为已经完成了
### .rejects
如果希望Promise返回rejected，需要使用`.rejects`匹配器。 它和`.resolves`匹配器是一样的使用方式。 如果 Promise 被拒绝，则测试将自动失败
```javascript
test('the fetch fails with an error', () => {
  return expect(fetchData()).rejects.toMatch('error')
})
```
